version: '2'

services:
  api:
    build: ./movieManagement
    restart: unless-stopped
    container_name: movieManagement_api
    ports:
      - "8087:8087"
    depends_on:
      - mariadb
    networks:
      - polytech

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=glopglop
      - MYSQL_DATABASE=lf
      - MYSQL_USER=lf
      - MYSQL_PASSWORD=1234
    networks:
      - polytech

networks:
  polytech:

volumes:
  mariadb: